<?php
/**
 * Infractor
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SAI Sistema de Administracion de Infracciones - Acta Digital
 *
 * VersiÃ³n REST del web service de DGAI que recibe acta de infracciones para incorporarlas al SAI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: scarabetta@buenosaires.gob.ar
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Infractor Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Infractor implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Infractor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'identidad' => '\Swagger\Client\Model\Persona',
        'fecha_nacimiento' => '\Swagger\Client\Model\FechaNacimiento',
        'correo_electronico' => '\Swagger\Client\Model\Email',
        'domicilio' => '\Swagger\Client\Model\Direccion'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'identidad' => null,
        'fecha_nacimiento' => null,
        'correo_electronico' => null,
        'domicilio' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identidad' => 'identidad',
        'fecha_nacimiento' => 'fechaNacimiento',
        'correo_electronico' => 'correoElectronico',
        'domicilio' => 'domicilio'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identidad' => 'setIdentidad',
        'fecha_nacimiento' => 'setFechaNacimiento',
        'correo_electronico' => 'setCorreoElectronico',
        'domicilio' => 'setDomicilio'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identidad' => 'getIdentidad',
        'fecha_nacimiento' => 'getFechaNacimiento',
        'correo_electronico' => 'getCorreoElectronico',
        'domicilio' => 'getDomicilio'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['identidad'] = isset($data['identidad']) ? $data['identidad'] : null;
        $this->container['fecha_nacimiento'] = isset($data['fecha_nacimiento']) ? $data['fecha_nacimiento'] : null;
        $this->container['correo_electronico'] = isset($data['correo_electronico']) ? $data['correo_electronico'] : null;
        $this->container['domicilio'] = isset($data['domicilio']) ? $data['domicilio'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identidad
     *
     * @return \Swagger\Client\Model\Persona
     */
    public function getIdentidad()
    {
        return $this->container['identidad'];
    }

    /**
     * Sets identidad
     *
     * @param \Swagger\Client\Model\Persona $identidad identidad
     *
     * @return $this
     */
    public function setIdentidad($identidad)
    {
        $this->container['identidad'] = $identidad;

        return $this;
    }

    /**
     * Gets fecha_nacimiento
     *
     * @return \Swagger\Client\Model\FechaNacimiento
     */
    public function getFechaNacimiento()
    {
        return $this->container['fecha_nacimiento'];
    }

    /**
     * Sets fecha_nacimiento
     *
     * @param \Swagger\Client\Model\FechaNacimiento $fecha_nacimiento fecha_nacimiento
     *
     * @return $this
     */
    public function setFechaNacimiento($fecha_nacimiento)
    {
        $this->container['fecha_nacimiento'] = $fecha_nacimiento;

        return $this;
    }

    /**
     * Gets correo_electronico
     *
     * @return \Swagger\Client\Model\Email
     */
    public function getCorreoElectronico()
    {
        return $this->container['correo_electronico'];
    }

    /**
     * Sets correo_electronico
     *
     * @param \Swagger\Client\Model\Email $correo_electronico correo_electronico
     *
     * @return $this
     */
    public function setCorreoElectronico($correo_electronico)
    {
        $this->container['correo_electronico'] = $correo_electronico;

        return $this;
    }

    /**
     * Gets domicilio
     *
     * @return \Swagger\Client\Model\Direccion
     */
    public function getDomicilio()
    {
        return $this->container['domicilio'];
    }

    /**
     * Sets domicilio
     *
     * @param \Swagger\Client\Model\Direccion $domicilio domicilio
     *
     * @return $this
     */
    public function setDomicilio($domicilio)
    {
        $this->container['domicilio'] = $domicilio;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


