<?php
/**
 * ActaVariosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SAI Sistema de Administracion de Infracciones - Acta Digital
 *
 * VersiÃ³n REST del web service de DGAI que recibe acta de infracciones para incorporarlas al SAI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: scarabetta@buenosaires.gob.ar
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ActaVariosTest Class Doc Comment
 *
 * @category    Class
 * @description ActaVarios
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActaVariosTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActaVarios"
     */
    public function testActaVarios()
    {
    }

    /**
     * Test attribute "modalidad_acta"
     */
    public function testPropertyModalidadActa()
    {
    }

    /**
     * Test attribute "nro_acta"
     */
    public function testPropertyNroActa()
    {
    }

    /**
     * Test attribute "expediente_electronico"
     */
    public function testPropertyExpedienteElectronico()
    {
    }

    /**
     * Test attribute "fecha_acta"
     */
    public function testPropertyFechaActa()
    {
    }

    /**
     * Test attribute "denuncia"
     */
    public function testPropertyDenuncia()
    {
    }

    /**
     * Test attribute "clausura"
     */
    public function testPropertyClausura()
    {
    }

    /**
     * Test attribute "secuestro"
     */
    public function testPropertySecuestro()
    {
    }

    /**
     * Test attribute "decomiso"
     */
    public function testPropertyDecomiso()
    {
    }

    /**
     * Test attribute "descripcion"
     */
    public function testPropertyDescripcion()
    {
    }

    /**
     * Test attribute "imagen_acta"
     */
    public function testPropertyImagenActa()
    {
    }

    /**
     * Test attribute "imagenes_prueba"
     */
    public function testPropertyImagenesPrueba()
    {
    }

    /**
     * Test attribute "acta_secuestro"
     */
    public function testPropertyActaSecuestro()
    {
    }

    /**
     * Test attribute "inspector"
     */
    public function testPropertyInspector()
    {
    }

    /**
     * Test attribute "infraccion"
     */
    public function testPropertyInfraccion()
    {
    }

    /**
     * Test attribute "atendido_por"
     */
    public function testPropertyAtendidoPor()
    {
    }

    /**
     * Test attribute "testigos"
     */
    public function testPropertyTestigos()
    {
    }
}
