<?php
/**
 * InfractorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SAI Sistema de Administracion de Infracciones - Acta Digital
 *
 * VersiÃ³n REST del web service de DGAI que recibe acta de infracciones para incorporarlas al SAI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: scarabetta@buenosaires.gob.ar
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InfractorTest Class Doc Comment
 *
 * @category    Class
 * @description Infractor
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InfractorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Infractor"
     */
    public function testInfractor()
    {
    }

    /**
     * Test attribute "identidad"
     */
    public function testPropertyIdentidad()
    {
    }

    /**
     * Test attribute "fecha_nacimiento"
     */
    public function testPropertyFechaNacimiento()
    {
    }

    /**
     * Test attribute "correo_electronico"
     */
    public function testPropertyCorreoElectronico()
    {
    }

    /**
     * Test attribute "domicilio"
     */
    public function testPropertyDomicilio()
    {
    }
}
